# Generated by Django 3.2.3 on 2021-10-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=40)),
                ('book_author', models.CharField(max_length=40)),
                ('book_code', models.CharField(max_length=45)),
                ('date_issue', models.DateTimeField()),
            ],
        ),
    ]
